//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoTapes
    {
        public int Id { get; set; }
        public string NameVideotapes { get; set; }
        public Nullable<int> IDDateVideotapes { get; set; }
        public Nullable<int> IDindormationTapes { get; set; }
    
        public virtual DateVideoTapes DateVideoTapes { get; set; }
        public virtual InformationTapes InformationTapes { get; set; }
    }
}
